version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3.11.15-management
#    container_name: "rabbitmq"
#    hostname: rabbitmq
    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=rmuser
#      - RABBITMQ_DEFAULT_PASS=rmpassword
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
#      volumes:
#        - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672""
      - "15672:15672"
    networks:
      - tg_bot


networks:
  tg_bot:
    driver: bridge

  #docker run --rm --hostname my-rabbit2 --name rabbit3.11.15 rabbitmq:3.11.15-management -p 5672:5672